// Objective-C API for talking to github.com/coming-chat/go-runes-api/rune Go package.
//   gobind -lang=objc github.com/coming-chat/go-runes-api/rune
//
// File is generated by gobind. Do not edit.

#ifndef __Rune_H__
#define __Rune_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Base.objc.h"
#include "Btc.objc.h"

@class RuneApi;
@class RuneBalance;
@class RuneBalanceArray;
@class RuneInfo;
@class RuneTransferTransaction;

@interface RuneApi : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)url;
@property (nonatomic) NSString* _Nonnull url;
/**
 * 查询一个地址下某个 rune 的 balance
 */
- (RuneBalance* _Nullable)runeBalance:(NSString* _Nullable)owner runeName:(NSString* _Nullable)runeName error:(NSError* _Nullable* _Nullable)error;
/**
 * 查询一个地址下所有的 rune balance
 */
- (RuneBalanceArray* _Nullable)runeBalances:(NSString* _Nullable)owner error:(NSError* _Nullable* _Nullable)error;
/**
 * 使用 rune 名称查询 rune 信息
 */
- (RuneInfo* _Nullable)runeInfo:(NSString* _Nullable)name error:(NSError* _Nullable* _Nullable)error;
/**
 * 使用 rune id 查询 rune 信息
 */
- (RuneInfo* _Nullable)runeInfoById:(NSString* _Nullable)id_ error:(NSError* _Nullable* _Nullable)error;
/**
 * 构建 rune 转账交易
@param postage: the rune utxo's satoshi value, default is 546
 */
- (RuneTransferTransaction* _Nullable)transferRunes:(NSString* _Nullable)sender receiver:(NSString* _Nullable)receiver runeName:(NSString* _Nullable)runeName amount:(NSString* _Nullable)amount feeRate:(double)feeRate postage:(long)postage error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * rune balance
 */
@interface RuneBalance : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull address;
@property (nonatomic) NSString* _Nonnull balance;
@property (nonatomic) int16_t divisibility;
@property (nonatomic) BOOL hasInscription;
@property (nonatomic) NSString* _Nonnull rune;
@property (nonatomic) NSString* _Nonnull symbol;
- (NSString* _Nonnull)balanceWithDecimal;
- (NSString* _Nonnull)jsonString;
- (BOOL)unmarshalJSON:(NSData* _Nullable)data error:(NSError* _Nullable* _Nullable)error;
@end

@interface RuneBalanceArray : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field BalanceArray.AnyArray with unsupported type: github.com/coming-chat/wallet-SDK/core/base/inter.AnyArray[*github.com/coming-chat/go-runes-api/rune.Balance]

- (void)append:(RuneBalance* _Nullable)value;
- (long)count;
- (NSString* _Nonnull)jsonString;
- (NSData* _Nullable)marshalJSON:(NSError* _Nullable* _Nullable)error;
- (RuneBalance* _Nullable)remove:(long)index;
- (void)setValue:(RuneBalance* _Nullable)value index:(long)index;
- (BOOL)unmarshalJSON:(NSData* _Nullable)data error:(NSError* _Nullable* _Nullable)error;
- (RuneBalance* _Nullable)valueAt:(long)index;
@end

/**
 * rune info
 */
@interface RuneInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull runeId;
@property (nonatomic) int64_t block;
@property (nonatomic) int64_t burned;
@property (nonatomic) int16_t divisibility;
@property (nonatomic) NSString* _Nonnull etching;
@property (nonatomic) int64_t mints;
@property (nonatomic) int64_t number;
@property (nonatomic) int64_t premine;
@property (nonatomic) NSString* _Nonnull spacedRune;
@property (nonatomic) NSString* _Nonnull symbol;
@property (nonatomic) int64_t timestamp;
@property (nonatomic) double progress;
- (NSString* _Nonnull)jsonString;
@end

@interface RuneTransferTransaction : NSObject <goSeqRefInterface, BaseJsonable, BaseTransaction> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull commitId;
@property (nonatomic) NSString* _Nonnull commitPsbt;
@property (nonatomic) int64_t networkFee;
@property (nonatomic) int64_t satpointFee;
@property (nonatomic) int64_t serviceFee;
@property (nonatomic) int64_t commitFee;
@property (nonatomic) int64_t commitVsize;
@property (nonatomic) BtcBrc20CommitCustom* _Nullable commitCustom;
- (BaseOptionalString* _Nullable)jsonString:(NSError* _Nullable* _Nullable)error;
- (BaseOptionalString* _Nullable)signWithAccount:(id<BaseAccount> _Nullable)account error:(NSError* _Nullable* _Nullable)error;
- (id<BaseSignedTransaction> _Nullable)signedTransactionWithAccount:(id<BaseAccount> _Nullable)account error:(NSError* _Nullable* _Nullable)error;
/**
 * return networkFee + serviceFee + satpointFee
 */
- (int64_t)totalFee;
@end

FOUNDATION_EXPORT NSString* _Nonnull const RuneUrlMainnet;
FOUNDATION_EXPORT NSString* _Nonnull const RuneUrlTestnet;

FOUNDATION_EXPORT RuneApi* _Nullable RuneNewApi(NSString* _Nullable url);

#endif
