// Objective-C API for talking to github.com/coming-chat/go-dmens-sdk/dmens Go package.
//   gobind -lang=objc github.com/coming-chat/go-dmens-sdk/dmens
//
// File is generated by gobind. Do not edit.

#ifndef __Dmens_H__
#define __Dmens_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Base.objc.h"
#include "Sui.objc.h"

@class DmensConfiguration;
@class DmensNote;
@class DmensNotePage;
@class DmensNoteStatus;
@class DmensPoster;
@class DmensPosterConfig;
@class DmensProfile;
@class DmensQuery;
@class DmensUserFollowCount;
@class DmensUserInfo;
@class DmensUserPage;
@protocol DmensJsonable;
@class DmensJsonable;

@protocol DmensJsonable <NSObject>
- (NSString* _Nonnull)jsonString:(NSError* _Nullable* _Nullable)error;
@end

@interface DmensConfiguration : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull name;
@property (nonatomic) NSString* _Nonnull fullNodeUrl;
@property (nonatomic) NSString* _Nonnull graphqlUrl;
@property (nonatomic) NSString* _Nonnull contractAddress;
@property (nonatomic) NSString* _Nonnull globalProfileId;
@property (nonatomic) NSString* _Nonnull globalProfileTableId;
@property (nonatomic) BOOL isMainNet;
@end

@interface DmensNote : NSObject <goSeqRefInterface, BaseAniable, DmensJsonable> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int64_t createTime;
@property (nonatomic) NSString* _Nonnull noteId;
@property (nonatomic) long action;
@property (nonatomic) NSString* _Nonnull text;
@property (nonatomic) NSString* _Nonnull poster;
@property (nonatomic) NSString* _Nonnull refId;
@property (nonatomic) DmensNoteStatus* _Nullable status;
- (BaseAny* _Nullable)asAny;
- (NSString* _Nonnull)jsonString:(NSError* _Nullable* _Nullable)error;
@end

@interface DmensNotePage : NSObject <goSeqRefInterface, DmensJsonable> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field NotePage.Notes with unsupported type: []*github.com/coming-chat/go-dmens-sdk/dmens.Note

@property (nonatomic) NSString* _Nonnull currentCursor;
@property (nonatomic) long currentCount;
@property (nonatomic) long totalCount;
- (NSString* _Nonnull)jsonString:(NSError* _Nullable* _Nullable)error;
- (BaseAnyArray* _Nullable)noteArray;
@end

@interface DmensNoteStatus : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull noteId;
@property (nonatomic) NSString* _Nonnull viewer;
@property (nonatomic) long replyCount;
@property (nonatomic) long repostCount;
@property (nonatomic) long likeCount;
/**
 * Whether the viewer reposted it
 */
@property (nonatomic) BOOL isReposted;
/**
 * Whether the viewer liked it
 */
@property (nonatomic) BOOL isLiked;
@end

@interface DmensPoster : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(DmensPosterConfig* _Nullable)posterConfig configuration:(DmensConfiguration* _Nullable)configuration;
- (nullable instancetype)initWithAddress:(NSString* _Nullable)posterAddress configuration:(DmensConfiguration* _Nullable)configuration;
@property (nonatomic) DmensConfiguration* _Nullable configuration;
@property (nonatomic) DmensPosterConfig* _Nullable posterConfig;
/**
 * 批量查询 page 中所有 note 的状态，数据会直接同步到 page 中每一个 note 对象中
@param viewer the note's viewer, if the viewer is empty, the poster's address will be queried.
 */
- (BOOL)batchQueryNoteStatus:(DmensNotePage* _Nullable)page viewer:(NSString* _Nullable)viewer error:(NSError* _Nullable* _Nullable)error;
- (SuiTransaction* _Nullable)dmensFollow:(BaseStringArray* _Nullable)addresses error:(NSError* _Nullable* _Nullable)error;
- (SuiTransaction* _Nullable)dmensPost:(NSString* _Nullable)text error:(NSError* _Nullable* _Nullable)error;
- (SuiTransaction* _Nullable)dmensPostWithRef:(long)action text:(NSString* _Nullable)text refIdentifier:(NSString* _Nullable)refIdentifier error:(NSError* _Nullable* _Nullable)error;
- (SuiTransaction* _Nullable)dmensUnfollow:(BaseStringArray* _Nullable)addresses error:(NSError* _Nullable* _Nullable)error;
- (BOOL)fetchDmensGlobalConfig:(NSError* _Nullable* _Nullable)error;
/**
 * FetchDmensObjecId After ios or android call profileRegister and send that transaction,
this func should be recalled again to fetch the registered dmens object id
 */
- (BOOL)fetchDmensObjecId:(NSError* _Nullable* _Nullable)error;
- (BOOL)isRegister;
- (NSString* _Nonnull)makeQuery:(DmensQuery* _Nullable)q error:(NSError* _Nullable* _Nullable)error;
/**
 * @param pageSize The number of notes per page.
@param afterCursor Each page has a cursor, and you need to specify the cursor to get the next page of content, If you want to get the first page of content, pass in empty.
 */
- (DmensNotePage* _Nullable)queryAllNoteList:(long)pageSize afterCursor:(NSString* _Nullable)afterCursor error:(NSError* _Nullable* _Nullable)error;
- (DmensQuery* _Nullable)queryDmensGlobalConfig;
- (DmensQuery* _Nullable)queryDmensObjectId;
- (DmensNote* _Nullable)queryNoteById:(NSString* _Nullable)noteId error:(NSError* _Nullable* _Nullable)error;
/**
 * @param noteId the note's id
@param viewer the note's viewer, if the viewer is empty, the poster's address will be queried.
 */
- (DmensNoteStatus* _Nullable)queryNoteStatusById:(NSString* _Nullable)noteId viewer:(NSString* _Nullable)viewer error:(NSError* _Nullable* _Nullable)error;
- (DmensNotePage* _Nullable)queryNotesMyFollowed:(long)pageSize afterCursor:(NSString* _Nullable)afterCursor error:(NSError* _Nullable* _Nullable)error;
- (DmensNotePage* _Nullable)queryReplyNoteList:(NSString* _Nullable)noteId pageSize:(long)pageSize afterCursor:(NSString* _Nullable)afterCursor error:(NSError* _Nullable* _Nullable)error;
- (DmensNotePage* _Nullable)queryTrendNoteList:(long)pageSize afterCursor:(NSString* _Nullable)afterCursor error:(NSError* _Nullable* _Nullable)error;
- (DmensUserPage* _Nullable)queryTrendUserList:(long)pageSize error:(NSError* _Nullable* _Nullable)error;
/**
 * @param user If the user is empty, the poster's address will be queried.
 */
- (DmensUserFollowCount* _Nullable)queryUserFollowCount:(NSString* _Nullable)user error:(NSError* _Nullable* _Nullable)error;
/**
 * @param user If the user is empty, the poster's address will be queried.
 */
- (DmensUserPage* _Nullable)queryUserFollowers:(NSString* _Nullable)user pageSize:(long)pageSize afterCursor:(NSString* _Nullable)afterCursor error:(NSError* _Nullable* _Nullable)error;
/**
 * @param user If the user is empty, the poster's address will be queried.
 */
- (DmensUserPage* _Nullable)queryUserFollowing:(NSString* _Nullable)user pageSize:(long)pageSize afterCursor:(NSString* _Nullable)afterCursor error:(NSError* _Nullable* _Nullable)error;
/**
 * @param address If the address is empty, the poster's address will be queried.
 */
- (DmensUserInfo* _Nullable)queryUserInfoByAddress:(NSString* _Nullable)address error:(NSError* _Nullable* _Nullable)error;
/**
 * @param user If the user is empty, the poster's address will be queried.
 */
- (DmensNotePage* _Nullable)queryUserNoteList:(NSString* _Nullable)user pageSize:(long)pageSize afterCursor:(NSString* _Nullable)afterCursor error:(NSError* _Nullable* _Nullable)error;
- (DmensUserPage* _Nullable)queryUsersByName:(NSString* _Nullable)name pageSize:(long)pageSize afterCursor:(NSString* _Nullable)afterCursor error:(NSError* _Nullable* _Nullable)error;
- (SuiTransaction* _Nullable)register:(DmensProfile* _Nullable)profile error:(NSError* _Nullable* _Nullable)error;
@end

@interface DmensPosterConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)address;
@property (nonatomic) NSString* _Nonnull address;
@property (nonatomic) NSString* _Nonnull dmensNftId;
@end

@interface DmensProfile : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull name;
@property (nonatomic) NSString* _Nonnull bio;
@property (nonatomic) NSString* _Nonnull avatar;
@end

@interface DmensQuery : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull query;
@property (nonatomic) NSString* _Nonnull operationName;
// skipped field Query.Variables with unsupported type: map[string]interface{}

/**
 * 因为在 Variables 中使用 cursor 无法实现 `null cursor`, 因此将 cursor 单独取出来
cursor 为空时，表示 null
 */
@property (nonatomic) NSString* _Nonnull cursor;
- (NSString* _Nonnull)actualQueryString;
@end

@interface DmensUserFollowCount : NSObject <goSeqRefInterface, DmensJsonable> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull user;
@property (nonatomic) long followerCount;
@property (nonatomic) long followingCount;
- (NSString* _Nonnull)jsonString:(NSError* _Nullable* _Nullable)error;
@end

@interface DmensUserInfo : NSObject <goSeqRefInterface, BaseAniable, DmensJsonable> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull address;
@property (nonatomic) NSString* _Nonnull avatar;
@property (nonatomic) NSString* _Nonnull bio;
@property (nonatomic) NSString* _Nonnull name;
@property (nonatomic) NSString* _Nonnull nodeId;
- (BaseAny* _Nullable)asAny;
- (NSString* _Nonnull)jsonString:(NSError* _Nullable* _Nullable)error;
@end

@interface DmensUserPage : NSObject <goSeqRefInterface, DmensJsonable> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field UserPage.Users with unsupported type: []github.com/coming-chat/go-dmens-sdk/dmens.UserInfo

@property (nonatomic) NSString* _Nonnull currentCursor;
@property (nonatomic) long currentCount;
@property (nonatomic) long totalCount;
- (DmensUserInfo* _Nullable)firstObject;
- (NSString* _Nonnull)jsonString:(NSError* _Nullable* _Nullable)error;
- (BaseAnyArray* _Nullable)userArray;
@end

FOUNDATION_EXPORT const long DmensACTION_LIKE;
FOUNDATION_EXPORT const long DmensACTION_POST;
FOUNDATION_EXPORT const long DmensACTION_QUOTE_POST;
FOUNDATION_EXPORT const long DmensACTION_REPLY;
FOUNDATION_EXPORT const long DmensACTION_REPOST;
FOUNDATION_EXPORT const int64_t DmensActionLike;
FOUNDATION_EXPORT const int64_t DmensActionQuotePost;
FOUNDATION_EXPORT const int64_t DmensActionRePost;
FOUNDATION_EXPORT const int64_t DmensActionReply;
FOUNDATION_EXPORT NSString* _Nonnull const DmensFunctionRegister;

@interface Dmens : NSObject
+ (DmensConfiguration* _Nullable) devnetConfig;
+ (void) setDevnetConfig:(DmensConfiguration* _Nullable)v;

+ (NSError* _Nullable) errGetNullConfiguration;
+ (void) setErrGetNullConfiguration:(NSError* _Nullable)v;

+ (NSError* _Nullable) errUserNotRegistered;
+ (void) setErrUserNotRegistered:(NSError* _Nullable)v;

+ (DmensConfiguration* _Nullable) mainnetConfig;
+ (void) setMainnetConfig:(DmensConfiguration* _Nullable)v;

+ (DmensConfiguration* _Nullable) testnetConfig;
+ (void) setTestnetConfig:(DmensConfiguration* _Nullable)v;

@end

FOUNDATION_EXPORT DmensNote* _Nullable DmensAsNote(BaseAny* _Nullable any);

FOUNDATION_EXPORT DmensUserInfo* _Nullable DmensAsUserInfo(BaseAny* _Nullable a);

// skipped function JsonString with unsupported parameter or return types


FOUNDATION_EXPORT DmensPoster* _Nullable DmensNewPoster(DmensPosterConfig* _Nullable posterConfig, DmensConfiguration* _Nullable configuration, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT DmensPosterConfig* _Nullable DmensNewPosterConfig(NSString* _Nullable address);

FOUNDATION_EXPORT DmensPoster* _Nullable DmensNewPosterWithAddress(NSString* _Nullable posterAddress, DmensConfiguration* _Nullable configuration, NSError* _Nullable* _Nullable error);

@class DmensJsonable;

@interface DmensJsonable : NSObject <goSeqRefInterface, DmensJsonable> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (NSString* _Nonnull)jsonString:(NSError* _Nullable* _Nullable)error;
@end

#endif
