// Objective-C API for talking to go-defi-sdk/util Go package.
//   gobind -lang=objc go-defi-sdk/util
//
// File is generated by gobind. Do not edit.

#ifndef __Util_H__
#define __Util_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@interface Util : NSObject
+ (NSError* _Nullable) errAddress;
+ (void) setErrAddress:(NSError* _Nullable)v;

+ (NSError* _Nullable) errChainAccount;
+ (void) setErrChainAccount:(NSError* _Nullable)v;

+ (NSError* _Nullable) errChainNotFound;
+ (void) setErrChainNotFound:(NSError* _Nullable)v;

+ (NSError* _Nullable) errChainRpcURLMissing;
+ (void) setErrChainRpcURLMissing:(NSError* _Nullable)v;

+ (NSError* _Nullable) errExecutionSetting;
+ (void) setErrExecutionSetting:(NSError* _Nullable)v;

+ (NSError* _Nullable) errExecutionStopped;
+ (void) setErrExecutionStopped:(NSError* _Nullable)v;

+ (NSError* _Nullable) errInsufficientBalance;
+ (void) setErrInsufficientBalance:(NSError* _Nullable)v;

+ (NSError* _Nullable) errNumber;
+ (void) setErrNumber:(NSError* _Nullable)v;

+ (NSError* _Nullable) errUnsupportedAsset;
+ (void) setErrUnsupportedAsset:(NSError* _Nullable)v;

+ (NSError* _Nullable) errUnsupportedChainType;
+ (void) setErrUnsupportedChainType:(NSError* _Nullable)v;

+ (NSError* _Nullable) errUnsupportedStep;
+ (void) setErrUnsupportedStep:(NSError* _Nullable)v;

+ (NSError* _Nullable) errUnsupportedTool;
+ (void) setErrUnsupportedTool:(NSError* _Nullable)v;

@end

// skipped function AddressStringToMultiAddress with unsupported parameter or return types


/**
 * CompareBalanceStr
  -1 if x <  y
   0 if x == y
  +1 if x >  y
 */
FOUNDATION_EXPORT long UtilCompareBalanceStr(NSString* _Nullable x, NSString* _Nullable y);

#endif
